export const FETCH_DATA = 'FETCH_DATA';
export const ADD_MEETING = 'ADD_MEETING';
export const SELECT_BUILDING = 'SELECT_BUILDING';
export const SAVE_MEETING = 'SAVE_MEETING';
export const FETCH_TEMP_DATA = 'FETCH_TEMP_DATA';